export const backendRpcNames = {
  listAdminAssets: "list_admin_assets",
  resolveAssetByQrCode: "resolve_asset_by_qr_code",
  regenerateAssetQr: "regenerate_asset_qr",
  createBooking: "create_booking",
  cancelBooking: "cancel_booking",
  decideBooking: "decide_booking",
  checkoutBooking: "checkout_booking",
  returnBooking: "return_booking",
  listBorrowableResources: "list_borrowable_resources",
  listResourceSchedule: "list_resource_schedule",
  createBorrowing: "create_borrowing",
  cancelBorrowing: "cancel_borrowing",
  decideBorrowing: "decide_borrowing",
  checkoutBorrowing: "checkout_borrowing",
  getBorrowerQrPickup: "get_borrower_qr_pickup",
  checkoutBorrowingByQr: "checkout_borrowing_by_qr",
  returnBorrowing: "return_borrowing",
  getBorrowingMonitor: "get_borrowing_monitor",
  getUsageAnalytics: "get_usage_analytics",
  listActivityLogs: "list_activity_logs",
  getPrintableReportData: "get_printable_report_data",
  createDefectReport: "create_defect_report",
  triageDefectReport: "triage_defect_report",
  ensureTicketThread: "ensure_ticket_thread",
  sendTicketMessage: "send_ticket_message",
  markNotificationRead: "mark_notification_read",
  resetMyActivityData: "reset_my_activity_data"
} as const;

export const backendRpcArgumentNames = {
  listAdminAssets: ["p_limit", "p_offset"],
  resolveAssetByQrCode: ["p_qr_code"],
  regenerateAssetQr: ["p_asset_id", "p_qr_code"],
  createBooking: ["p_asset_id", "p_requested_start_at", "p_requested_end_at", "p_purpose"],
  cancelBooking: ["p_booking_id"],
  decideBooking: ["p_booking_id", "p_status", "p_notes"],
  checkoutBooking: ["p_booking_id", "p_notes"],
  returnBooking: ["p_booking_id", "p_notes"],
  listBorrowableResources: ["p_start_at", "p_end_at", "p_resource_type", "p_location_id", "p_query"],
  listResourceSchedule: ["p_resource_type", "p_resource_id", "p_from", "p_to"],
  createBorrowing: ["p_resource_type", "p_resource_id", "p_requested_start_at", "p_requested_end_at", "p_purpose"],
  cancelBorrowing: ["p_borrowing_id"],
  decideBorrowing: ["p_borrowing_id", "p_status", "p_notes"],
  checkoutBorrowing: ["p_borrowing_id", "p_notes"],
  getBorrowerQrPickup: ["p_qr_code"],
  checkoutBorrowingByQr: ["p_qr_code", "p_borrowing_id", "p_notes"],
  returnBorrowing: ["p_borrowing_id", "p_notes"],
  getBorrowingMonitor: ["p_from", "p_to", "p_location_id", "p_resource_id", "p_statuses"],
  getUsageAnalytics: ["p_from", "p_to", "p_location_id", "p_asset_id"],
  listActivityLogs: ["p_from", "p_to", "p_limit", "p_offset"],
  getPrintableReportData: ["p_report_type", "p_from", "p_to", "p_location_id", "p_asset_id"],
  createDefectReport: ["p_asset_id", "p_title", "p_description"],
  triageDefectReport: ["p_defect_report_id", "p_status", "p_notes"],
  ensureTicketThread: ["p_subject_type", "p_booking_id", "p_defect_report_id"],
  sendTicketMessage: ["p_thread_id", "p_body"],
  markNotificationRead: ["p_notification_id"],
  resetMyActivityData: []
} as const;

export type BackendRpcKey = keyof typeof backendRpcNames;
export type BackendRpcName = (typeof backendRpcNames)[BackendRpcKey];
export type BackendRpcArgumentName = (typeof backendRpcArgumentNames)[BackendRpcKey][number];
